# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: eHabla Futbol
email: info@ehablafutbol.com
description: > # this means to ignore newlines until "baseurl:"
  ehabla Futbol combines compelling, real-world experiences with a social intelligence and advertising platform that utilizes the power of f√∫tbol to drive brand awareness and engagement with the Hispanic community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ehablafutbol.com" # the base hostname & protocol for your site
twitter_username: ""
github_username:  ""

# Build settings
markdown: kramdown

# Assets are being handled by Gulp
exclude: [assets]
keep_files: [assets]

# Contact 
contact_title: Let's Get Started
contact_desc: Thank you interest in eHabla Futbol. We are here to answer any questions you may have, so reach out to us and we'll respond as soon as we can.
